version: '3.8'

services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=NEWS.settings
      - DATABASE_URL=postgres://user:password@db:5432/mynewsdb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)" 
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - static-data:/app/staticfiles

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mynewsdb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certs:/letsencrypt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  static-data:
  traefik-certs:
